name: "dbt_retail"
version: "0.1.0"
config-version: 2

profile: "dbt_retail"

model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  dbt_retail:
    +materialized: view
    staging:
      +schema: retail_stg
      +materialized: view
    marts:
      +schema: retail_analytics
      +materialized: table

